### ISSUE TITLE
Non-web transactions

### ISSUE THREAD

**Issue by ashrestha91** [stevebartholomew/newrelic_moped#31]
I'm running trying to instrument the database queries run by my sidekiq workers.  I'm getting database instrumentation for my web transactions, but not for the workers.  I am getting web transactions for my application.

This is in sinatra, not rails.  I haven't had a chance to try this in rails.

Is newrelic_moped set up to report non-web transactions?

**Comment by piotr-sokolowski** [comment]
I don't see any reason why it shouldn't work. newrelic_moped is just addition to newrelic_rpm which should work for Sidekiq.
Do you see other information from your Sidekiq jobs in NewRelic and only database transactions are missing or all other information is missing as well ?

**Comment by ashrestha91** [comment]
Yeah, I see the Sidekiq workers as transactions in newrelic, with job arguments and trace details for net requests, but no database traces. 

After a second look at my newrelic logs, I'm seeing the log line that it's instrumenting Moped for my ui service only, though the file is being loaded.  Does the file need to be loaded at a particular time? I'm unfamiliar with how `DependencyDetection.defer` works.

**Comment by piotr-sokolowski** [comment]
This is indeed related to way how **defer** works.
Your problem will be most likely solved by requiring **newrelic_moped** before **newrelic_rpm**:

    require 'newrelic_moped'                                                                                              
    require 'newrelic_rpm'

Explanation:
It doesn't matter in Rails or in Sinatra because Rack is used and Rack instrumentation actuall calls **detect!** (https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/instrumentation/rack.rb#L107) by it's own. So **detect!** is called twice - On newrelic_rpm initialization and second time in registering Rack instrumentation.
When Rack is not used because it's Sidekiq or Resque or even just tux/irb, it's calling **detect!** just once. That's why **newrelic_moped** needs to be required before this.
This is actually related to #14 - I'll update the README.
Hope this will help you.

**Comment by ashrestha91** [comment]
Thanks, that fixed it!  I saw that issue previously, but I was also requiring the newrelic_rpm and newrelic_moped gems too early.
